name: Check Tests

on:
   pull_request:
    paths:
      - 'IoT/**' 

jobs:
  check-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Install Check
      run: sudo apt-get install check  # Install the Check unit testing framework

    - name: Build and run tests with Check
      run: |
        cd Iot/Test
        make  # Replace with your build command
      env:
        CHECK: "1"

    - name: Check test results
      run: |
        cd Iot/Test
        ./main  # Replace with the test runner command when we will know it

    - name: Set status checks
      if: failure()
      run: echo "Check tests failed. Please review the test results."
